server:
  port: 8861

spring:
  application:
    name: zuul-server

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}

zuul:
  routes:
    monitor-server:
      path: /monitor/**
      serviceId: monitor-server
