server:
  port: 9999

spring:
  application:
    name: test-server

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}


#ribbon的负载均衡策略
monitor-server:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    # 轮询：com.netflix.loadbalancer.RandomRule
    # 随机：com.netflix.loadbalancer.RandomRule


feign:
  hystrix:
    enabled: true
hystrix:
  threadpool:
    default:
      coreSize: 100
      maximumSize: 100
      maxQueueSize: 0
  command:
    # default:全局有效;可以指定HystrixCommonKey有效，格式:类名#方法名(参数类型)
    MonitorService#getMsg():
      execution:
        timeout:
          enable: true
        isolation:
          thread:
            timeoutInMilliseconds: 9000

############################feign日志级别设置
#logging:
  #level:
    #sun.study.note.service: debug
