server:
  port: 9999

spring:
  application:
    name: test-server

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}

feign:
  hystrix:
    enabled: true

hystrix:
  threadpool:
    default:
      coreSize: 100
      maximumSize: 100
      maxQueueSize: 0
  command:
    # default:全局有效;可以指定HystrixCommonKey有效，格式:类名#方法名(参数类型)
    MonitorService#getData():
      execution:
        timeout:
          enable: true
        isolation:
          thread:
            timeoutInMilliseconds: 300
