server:
  port: 8084
  tomcat:
    max-connections: 3000

spring:
  application:
    name: monitor-server

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
